repaired fetchChats crash
crash message:
\simplechat\server\db.js:135
     if (chatIDs.chats.length > 0) {
                 ^

 TypeError: Cannot read properties of null (reading 'chats')

fix: chatIDs is [] instead of null